name: "Release"
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build ${{ github.workspace }}/src/SharpCLIParser --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack ${{ github.workspace }}/src/SharpCLIParser --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push to nuget
      run: dotnet nuget push SharpCLIParser.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${API_KEY}
      env:
        GITHUB_TOKEN: ${{ secrets.API_KEY }}
    - name: Push to github
      run: dotnet nuget push SharpCLIParser.${VERSION}.nupkg --source https://nuget.pkg.github.com/onboardcode/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}